version: '3'

services:

        web:
                build: ./web
                environment:
                        - APACHE_RUN_USER=#1000
                volumes:
                        - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
                ports:
                        - ${APP_PORT}:80
                working_dir: ${APP_PATH_CONTAINER}

        db:
                image: mariadb
                environment:
                        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
                volumes:
                        - ${DB_PATH_HOST}:/var/lib/mysql

        adminer:
                image: adminer
                ports:
                        - ${ADMINER_PORT}:8080

        composer:
                image: composer:1.8.5
                volumes:
                        - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
                working_dir: ${APP_PATH_CONTAINER}
                command: composer install



